version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"  # Exposes the app on port 3000
    environment:
      - NODE_ENV=production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
